name: Deploy to staging
on: workflow_dispatch

jobs:
  confirm-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "Doing nothing"
  update-staging:
    permissions: write-all
    needs: confirm-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Set staging to equal main
        run: |
          git fetch origin staging
          git checkout staging
          git reset --hard origin/main
          git push --force
